"""
Django settings for xylem project.

Generated by "django-admin startproject" using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os, random, string, logging
from dotenv import load_dotenv
from pathlib import Path

from django.contrib.messages import constants as message_constants
import xylem.custom_messages.constants as custom_message_constants

load_dotenv()
XYLEM_MODE = os.getenv("XYLEM_MODE")
BASE_DIR = os.getenv("BASE_DIR")

XYLEM_MODE_DIC ={
    "development_mode": os.getenv("DEVELOPMENT_MODE_STR"),
    "testing_mode": os.getenv("TESTING_MODE_STR"),
    "deployment_mode": os.getenv("DEPLOYMENT_MODE_STR"),
}


load_dotenv(os.path.join(BASE_DIR, f"{XYLEM_MODE}.env"))

# Build paths inside the project like this: BASE_DIR / "subdir".

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECRET_KEY = "".join(random.choice(string.ascii_lowercase) for i in range(111))

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = bool(os.getenv("SECRET_KEY"))

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",")]



# Application definition
INSTALLED_APPS = [
    # "admin_datta.apps.AdminDattaConfig", 
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "celery",
    "xylem_apps.a000_xylem_master",
    "xylem_apps.a001_qa_report_and_reprocess",
    "xylem_apps.a002_sbs_rejection_entry_and_rework",
    "xylem_apps.a003_smart_alerts",
    "xylem_apps.a004_tools_management_system",
    "xylem_apps.a005_qa_patrol_check",
    "xylem_apps.a006_4m_digitalization",
    "xylem_apps.a007_oee_monitoring",
    "xylem_apps.a008_home_schemer",
    "xylem_apps.a009_building_management_system",
    "xylem_apps.a010_poka_yoke_monitoring",
    "xylem_apps.a011_workflows",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "xylem_apps.a000_xylem_master.middleware.UserActivityMiddleware",
]

ROOT_URLCONF = "xylem.urls"

# a000_xylem_master
# a001_qa_report_and_reprocess
# a002_sbs_rejection_entry_and_rework
# a003_smart_alerts
# a004_tools_management_system
# a005_qa_patrol_check
# a006_4m_digitalization
# a007_oee_monitoring
# a008_home_schemer
# a009_building_management_system
# a010_poka_yoke_monitoring
# a011_workflows

DATABASE_ROUTERS = [
    "xylem_apps.a000_xylem_master.models_router.A000Router",
    "xylem_apps.a001_qa_report_and_reprocess.models_router.A001Router",
    "xylem_apps.a002_sbs_rejection_entry_and_rework.models_router.A002Router",
    "xylem_apps.a003_smart_alerts.models_router.A003Router",
    "xylem_apps.a004_tools_management_system.models_router.A004Router",
    "xylem_apps.a005_qa_patrol_check.models_router.A005Router",
    "xylem_apps.a006_4m_digitalization.models_router.A006Router",
    "xylem_apps.a007_oee_monitoring.models_router.A007Router",
    "xylem_apps.a008_home_schemer.models_router.A008Router",
    "xylem_apps.a009_building_management_system.models_router.A009Router",
    "xylem_apps.a010_poka_yoke_monitoring.models_router.A010Router",
    "xylem_apps.a011_workflows.models_router.A011Router",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join( BASE_DIR, "xylem", "xylem_apps", "a000_xylem_master", "templates" ),
            os.path.join( BASE_DIR, "xylem", "xylem_apps", "a000_xylem_master", "templatetags" ),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "xylem.context_processors.custom_vars",
            ],
        },
    },
]

MESSAGE_TAGS = {
    message_constants.DEBUG: "secondary",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    custom_message_constants.SUCCESS_DISMISSABLE: "success",
    custom_message_constants.DANGER_DISMISSABLE: "danger",
    custom_message_constants.INFO_DISMISSABLE: "info",
    custom_message_constants.SUCCESS_MODAL_MESSAGE: "success",
    custom_message_constants.DANGER_MODAL_MESSAGE: "danger",
    custom_message_constants.INFO_MODAL_MESSAGE: "info",
}

WSGI_APPLICATION = "xylem.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_host = os.getenv("DATABASE_HOST")
database_username = os.getenv("DATABASE_USERNAME")
database_password = os.getenv("DATABASE_PASSWORD")

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a000_xylem_master",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "cache_db": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "cache_db",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a001_qa_report_and_reprocess": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a001_qa_report_and_reprocess",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a002_sbs_rejection_entry_and_rework": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a002_sbs_rejection_entry_and_rework",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a003_smart_alerts": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a003_smart_alerts",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a004_tools_management_system": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a004_tools_management_system",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a005_qa_patrol_check": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a005_qa_patrol_check",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a006_4m_digitalization": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a006_4m_digitalization",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a007_oee_monitoring": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a007_oee_monitoring",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a008_home_schemer": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a008_home_schemer",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a009_building_management_system": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a009_building_management_system",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a010_poka_yoke_monitoring": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a010_poka_yoke_monitoring",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
    "a011_workflows": {
        "ENGINE": "mssql",
        "HOST": database_host,
        "NAME": "a011_workflows",
        "USER": database_username,
        "PASSWORD": database_password,
        "PORT": "",
        "OPTIONS": {"driver": "ODBC Driver 13 for SQL Server"},
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a000_cache",
    },
    "a001": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a001_cache",
    },
    "a002": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a002_cache",
    },
    "a003": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a003_cache",
    },
    "a004": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a004_cache",
    },
    "a005": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a005_cache",
    },
    "a006": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a006_cache",
    },
    "a007": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a007_cache",
    },
    "a008": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a008_cache",
    },
    "a009": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a009_cache",
    },
    "a010": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a010_cache",
    },
    "a011": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "a011_cache",
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "xylem_apps/a000_xylem_master/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "xylem_static_deployment")

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "xylem", "xylem_apps", "a000_xylem_master", "static"),
)

# Base url to serve media files
MEDIA_URL = "/xylem_media/"

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, "xylem_media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "a000_xylem_master.UserProfile"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")


maximum_bytes_of_log_file = 5*1024*1024
maximum_backups_of_log_file = 2


class OnlyInfosFilter(logging.Filter):
    def filter(self, record):
        return record.levelno == logging.INFO


class OnlyWarningsFilter(logging.Filter):
    def filter(self, record):
        return record.levelno == logging.WARNING


class OnlyErrorsFilter(logging.Filter):
    def filter(self, record):
        return record.levelno == logging.ERROR
    

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} - {asctime} - {module} - {message} - {funcName} - Line no :{lineno}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "only_infos": {
            "()": OnlyInfosFilter,
        },
        "only_warnings": {
            "()": OnlyWarningsFilter,
        },
        "only_errors": {
            "()": OnlyErrorsFilter,
        },
    },
    "handlers": {
        "console": {
            "level": "ERROR",  # Log only errors or higher (ERROR, CRITICAL)
            "class": "logging.StreamHandler",
        },
        "django_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/logs/django_error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_bw_mail_han": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/mail_logs.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_xr_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/xr_info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_xr_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/xr_warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_xr_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/xr_error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_main_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/main_bw_info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_main_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/main_bw_warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_main_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/main_bw_error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a000_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a000_xylem_master/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a001_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a001_qa_report_and_reprocess/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a002_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a002_sbs_rejection_entry_and_rework/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a003_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a003_smart_alerts/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        }, 
        "a004_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a004_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a004_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a004_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a004_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a004_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a004_tools_management_system/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },      
        "a005_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a005_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a005_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a005_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a005_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a005_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a005_tools_management_system/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a006_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a006_4m_digitalization/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a007_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a007_oee_monitoring/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a008_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a008_home_schemer/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a009_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a009_building_management_system/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a010_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a010_poka_yoke_monitoring/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_bw_info_han": {
            "filters": ["only_infos"],
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/background_works/logs/info.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_bw_warning_han": {
            "filters": ["only_warnings"],
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/background_works/logs/warning.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        },
        "a011_bw_error_han": {
            "filters": ["only_errors"],
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "xylem_apps/a011_workflows/background_works/logs/error.log",
            "maxBytes": maximum_bytes_of_log_file, 
            "backupCount": maximum_backups_of_log_file,
            "delay": True,
            "formatter": "verbose",
        }, 
    },
    "loggers": {
        "django": {
            "handlers": ["console", "django_error_han"],
            "level": "INFO",
            "propagate": True
        },
        "a000": {
            "handlers": ["a000_info_han", "a000_warning_han", "a000_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a000_main_bw": {
            "handlers": ["a000_main_bw_info_han", "a000_main_bw_warning_han", "a000_main_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a000_bw": {
            "handlers": ["a000_bw_info_han", "a000_bw_warning_han", "a000_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "mail_handler": {
            "handlers": ["a000_bw_mail_han"],
            "level": "INFO",
            "propagate": True
        },
        "xylem_remote_handler": {
            "handlers": ["a000_xr_info_han", "a000_xr_warning_han", "a000_xr_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "background_worker": {
            "handlers": ["a000_xr_info_han", "a000_xr_warning_han", "a000_xr_error_han",],
            "level": "INFO",
            "propagate": True
        },

        "a001": {
            "handlers": ["a001_info_han", "a001_warning_han", "a001_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a001_bw": {
            "handlers": ["a001_bw_info_han", "a001_bw_warning_han", "a001_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a002": {
            "handlers": ["a002_info_han", "a002_warning_han", "a002_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a002_bw": {
            "handlers": ["a002_bw_info_han", "a002_bw_warning_han", "a002_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a003": {
            "handlers": ["a003_info_han", "a003_warning_han", "a003_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a003_bw": {
            "handlers": ["a003_bw_info_han", "a003_bw_warning_han", "a003_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a004": {
            "handlers": ["a004_info_han", "a004_warning_han", "a004_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a004_bw": {
            "handlers": ["a004_bw_info_han", "a004_bw_warning_han", "a004_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a005": {
            "handlers": ["a005_info_han", "a005_warning_han", "a005_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a005_bw": {
            "handlers": ["a005_bw_info_han", "a005_bw_warning_han", "a005_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a006": {
            "handlers": ["a006_info_han", "a006_warning_han", "a006_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a006_bw": {
            "handlers": ["a006_bw_info_han", "a006_bw_warning_han", "a006_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a007": {
            "handlers": ["a007_info_han", "a007_warning_han", "a007_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a007_bw": {
            "handlers": ["a007_bw_info_han", "a007_bw_warning_han", "a007_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a008": {
            "handlers": ["a008_info_han", "a008_warning_han", "a008_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a008_bw": {
            "handlers": ["a008_bw_info_han", "a008_bw_warning_han", "a008_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a009": {
            "handlers": ["a009_info_han", "a009_warning_han", "a009_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a009_bw": {
            "handlers": ["a009_bw_info_han", "a009_bw_warning_han", "a009_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a010": {
            "handlers": ["a010_info_han", "a010_warning_han", "a010_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a010_bw": {
            "handlers": ["a010_bw_info_han", "a010_bw_warning_han", "a010_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a011": {
            "handlers": ["a011_info_han", "a011_warning_han", "a011_error_han",],
            "level": "INFO",
            "propagate": True
        },
        "a011_bw": {
            "handlers": ["a011_bw_info_han", "a011_bw_warning_han", "a011_bw_error_han",],
            "level": "INFO",
            "propagate": True
        },
        
    },
}

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"


# Deployment with security
# SECURE_HSTS_SECONDS = 2
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_PRELOAD = True        


# # Time (in seconds) before the session expires due to inactivity
# SESSION_COOKIE_AGE = 1800  # 30 minutes

# # Whether the session should expire when the user closes the browser
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# # Whether to update the session expiry time on every request
# SESSION_SAVE_EVERY_REQUEST = True